# Generated by Django 5.0.4 on 2024-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_categoryimg_categorydb_category_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, max_length=100, null=True)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='productspics')),
            ],
        ),
    ]
