# Generated by Django 5.0.4 on 2024-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_registerationdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
